### ISSUE TITLE
Desired features for al-folio 1.0

### ISSUE THREAD

**Issue by alshedivat** [alshedivat/al-folio#85]
This issue tracks progress toward 1.0 upgrade of al-folio.

**TODOs:**
- [x] Improved responsive design (#87).
- [x] New [distill.pub](https://distill.pub/)-style post template (see demo [here](https://sailinglab.github.io/pgm-spring-2019/notes/lecture/)).
- [ ] Option to use the theme in a single-page mode vs. multi-page mode (using [singlepage-jekyll](https://github.com/JCB-K/singlepage-jekyll) or a similar plugin).
- [ ] Support for jupyter notebooks in the posts/pages (using [jekyll-jupyter-notebook](https://github.com/red-data-tools/jekyll-jupyter-notebook)).
- [x] Support for GitHub metadata (using [github-metadata](https://github.com/jekyll/github-metadata)) (#121)
- [x] Support for Twitter cards (using [jekyll-twitter-plugin](https://github.com/rob-murray/jekyll-twitter-plugin)) (#120)
- [ ] Automatic generation of the CV from a YAML template.

**Note:** The progress will be as time permits. Suggestions and contributions are welcome (please submit PRs to the `dev` branch).

**Comment by sangheek16** [comment]
@alshedivat Hi, Thanks so much for sharing your theme! I'm working on the bibliography section, and I was wondering if we can include other classes than @article in the bibliography. I tried e.g., @inproceedings, @phdthesis, etc. but it seems these formats aren't recognized.

**Comment by alshedivat** [comment]
That's strange, `@inproceedings` and `@thesis` does work when I swap `@article` to `@inproceedings` on the demo page. If you run into any bugs/issues, please post on [gitter](https://gitter.im/alshedivat/al-folio) or open a separate issue here.

**Comment by sangheek16** [comment]
@alshedivat Thanks! And sorry, please feel free to delete my post.

**Comment by Jongwoo-Shim** [comment]
In regards to the jupyter support : https://github.com/red-data-tools/jekyll-jupyter-notebook/issues/4

I don't believe that we'd be able to add support for jupyter notebooks directly until the dependency is updated to allow for it to be run on safe mode, and to work with a base directory.

**Comment by alshedivat** [comment]
Closing this as it's easier to track of features in separate issues. Also, we'll keep `0.x.x` versioning for now.
